default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: <%= ENV['PSQL_ROLE'] %>
  password: <%= ENV['PSQL_PASSWD'] %>

development:
  <<: *default
  database: city_event_development

test:
  <<: *default
  database: city_event_test

production:
  <<: *default
  database: city_event_production